# Generated by Django 4.0.5 on 2022-06-03 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_topic_user_topics_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topics_pinned',
            field=models.CharField(default='0000000000000000000000000000000', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='topics_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('problem_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
