# Generated by Django 4.0.5 on 2022-06-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_topics_pinned_alter_user_topics_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='palette',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
