# Generated by Django 4.0.5 on 2022-06-04 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.TextField(blank=True, null=True)),
                ('problem_id', models.IntegerField(null=True)),
                ('problem_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='topics_status',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='probleminfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
