# Generated by Django 4.0.5 on 2022-12-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
