# Generated by Django 4.0.5 on 2022-06-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_topics_status_user_problem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='problem_status',
            new_name='topics_status',
        ),
    ]
