# Generated by Django 4.0.5 on 2022-12-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tokens_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
