# Generated by Django 4.0.5 on 2022-06-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_problem_status_user_topics_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='topics_status',
            new_name='problem_status',
        ),
    ]
